name: Build & publish to PyPI

on:
  release:               # triggers when you create a GitHub Release
    types: [published]

permissions:
  contents: read
  id-token: write        # for trusted publishing (no password in logs)

jobs:
  build-and-publish:
    name: Build, test, and upload
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # ①  Set up Python
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # ②  Install build deps
    - run: |
        python -m pip install --upgrade pip build hatchling twine

    # ③  Build wheel + sdist
    - run: python -m build

    # ④  Test the wheel imports (optional but nice)
    - name: Smoke test
      run: |
        python -m venv /tmp/venv && . /tmp/venv/bin/activate
        pip3 install dist/*.whl
        python - <<'PY'
        import torchlaunch, sys
        print("import OK – version", torchlaunch.__version__)
        PY

    # ⑤  Publish to PyPI
    - name: Upload to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        # If you ever want to push *first* to TestPyPI:
        # repository-url: https://test.pypi.org/legacy/
